version: "3.9"

services:
  web:
    build: .
    container_name: fastapi_app
    env_file:
      - .env
    ports:
      - "8000:8000"
    depends_on:
      - db
      - redis
    volumes:
      - ./app:/app
    restart: always
    command: uvicorn main:app --host 0.0.0.0 --port 8000 --reload

  db:
    image: postgres:15
    container_name: postgres_db
    env_file:
      - .env
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: always

  redis:
    image: redis:7-alpine
    container_name: redis_db
    ports:
      - "6379:6379" 
    command: redis-server --appendonly yes
    volumes:
      - redis_data:/data
    restart: always

  celery:
    build: .
    container_name: celery_worker
    env_file:
      - .env
    depends_on:
      - redis
      - db
    volumes:
      - ./app:/app
    command: celery -A celery_worker.celery_worker.celery_app worker --loglevel=info
    restart: always

volumes:
  postgres_data:
  redis_data:
