"""Initial migration

Revision ID: 61b5625e4b37
Revises: 
Create Date: 2025-06-11 20:29:59.481489

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '61b5625e4b37'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_Users_id'), table_name='Users')
    op.drop_index(op.f('ix_Users_username'), table_name='Users')
    op.drop_table('Users')
    op.drop_index(op.f('ix_Tasks_id'), table_name='Tasks')
    op.drop_index(op.f('ix_Tasks_title'), table_name='Tasks')
    op.drop_table('Tasks')
    op.drop_index(op.f('ix_Books_id'), table_name='Books')
    op.drop_index(op.f('ix_Books_title'), table_name='Books')
    op.drop_table('Books')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Books',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('title', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('description', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('Books_pkey'))
    )
    op.create_index(op.f('ix_Books_title'), 'Books', ['title'], unique=True)
    op.create_index(op.f('ix_Books_id'), 'Books', ['id'], unique=False)
    op.create_table('Tasks',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('title', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('description', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('Tasks_pkey'))
    )
    op.create_index(op.f('ix_Tasks_title'), 'Tasks', ['title'], unique=False)
    op.create_index(op.f('ix_Tasks_id'), 'Tasks', ['id'], unique=False)
    op.create_table('Users',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('username', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('hashed_password', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('Users_pkey'))
    )
    op.create_index(op.f('ix_Users_username'), 'Users', ['username'], unique=True)
    op.create_index(op.f('ix_Users_id'), 'Users', ['id'], unique=False)
    # ### end Alembic commands ###
